### ISSUE TITLE
No Mac Version

### ISSUE THREAD

**Issue by ruchern** [Skibisky/RuneManager#21]
As stated in title. :(

**Comment by Skibisky** [comment]
This seems to be a common request.

I thought that because I used WinForms there was no way to Mac it without a rebuild in Java, but it seems it may be able to be ported via Mono.

[Looks promising](http://www.mono-project.com/docs/gui/winforms/porting-winforms-applications/)

**Comment by Skibisky** [comment]
Porting seems dead.

Someone has made a [Java optimizer](https://www.reddit.com/r/summonerswar/comments/4w5yu9/java_sw_rune_optimizer_update_ver_13/) which looks okay, should work fine on Mac.
