### ISSUE TITLE
1 3 5 Issues

### ISSUE THREAD

**Issue by cooye** [Skibisky/RuneManager#22]
When I change the criteria on a 3 slot for a build it changes the number of runes available for the 1 slot. Is this by design?

**Comment by Skibisky** [comment]
Yes, as the tool will detect how many of each set of rune is over all slots and exclude sets that can't be completed.

Eg. You include Energy (a 2-set) and the current filter only permits 1 Energy rune on slot 3 and 2 Energy runes on slot 1, along with runes of other sets.
When you change the filter for slot 3, it cuts out the Energy rune. As there is now only 1 slot, Slot 1, with Energy runes, the Energy set can never be completed as it requires at least 2 slots with permissible runes.

As a result, it removes the runes from that slot from being run, as those builds will be broken.

**Comment by Skibisky** [comment]
I just checked the code and it pulls out the runes regardless of AllowBroken, so I'll make that change.

How should I make this functionality more apparent/known?
