### ISSUE TITLE
Before value incorrect when atk buff is used

### ISSUE THREAD

**Issue by jipsuh** [Skibisky/RuneManager#26]
When running a build with atk buff enabled on a mon, the "Before" column shows values without the buff applied

A normal run:
![withoutatkbuf](https://user-images.githubusercontent.com/5948099/36075866-228cf53c-0f5d-11e8-9018-ce12d55a1ac3.PNG)

Same run with atk buff on:
![withatkbuf](https://user-images.githubusercontent.com/5948099/36075865-22728e5e-0f5d-11e8-8f47-92452a92e331.PNG)

Haven't tested if this applies to other buffs too. Makes it a bit difficult to see how much actual improvement my lushen is getting when the build changes.

Great piece of software by the way. I'm probably down to one sixth of time spent on getting my builds calculated for FRR compared to when I was still using SWOP.

**Comment by Skibisky** [comment]
Thanks for reminding me, I hadn't pushed that code up.

Fixed in c3337251fb26f68ad6825cfda0f5747f0c9b24a7  
Check out v0.6.2

**Comment by jipsuh** [comment]
Tested this out today and it seems to be working, thanks!

0.6.2 seems to have some UI freezing issues for me though. When calculating larger builds the UI becomes unresponsive for large periods of time (10 seconds to 1 minute maybe). But if I wait it out it will pass.

Also the new "Go fast" and "Fill only" tickboxes are laid out incorrectly if I fullscreen the app.
