### ISSUE TITLE
Same rune being reused in a later build

### ISSUE THREAD

**Issue by jipsuh** [Skibisky/RuneManager#28]
Noticed that there seems to be a bug in 0.6.2 that can cause the same rune to be reused by another mon.

What happened in my case was that:
- Rune was previously equipped on my Hwa and was now to be equipped onto Seara which is higher on priority
- Later when Hwa build was done calculating the loadout instructed to still use the same rune on Hwa

Switched back to 0.6.1 after which the loadouts for both mons were properly calculated.

**Comment by Skibisky** [comment]
Strange, I ran into that bug while developing 0.6.2 and fixed it for release. 
Sometimes if you stop, save loadouts, reopen the program, load loadouts, it can bug out a little.

If you submit your build.json and swarfarm.json to here I can try and take a closer look: 
https://script.google.com/macros/s/AKfycbwXVaXm9ASLxEoqjZAom4nmyMQa0ESH3j3oJfRX9YoiUceO2w/exec

**Comment by jipsuh** [comment]
I reinstalled everything and tried again. For some reason the issue didn't appear again.

I also switched from swproxy to swex for getting the game data. Don't know if that could have done anything. The swproxy version I used before was rather old.

**Comment by jipsuh** [comment]
Happened again so I was able to take a log. Uploaded it to the link you posted few months ago.

**Comment by Skibisky** [comment]
Can you also submit the builds.json?  
The log isn't the best to debug from

**Comment by claytondaley** [comment]
One way this could happen is by refreshing on the monster's tab.  The "usage" by existing loadouts wasn't refreshed.  Skibisky put a fix in place for this cause.

**Comment by claytondaley** [comment]
It looks like the refresh issue happens [here](https://github.com/Skibisky/RuneManager/blob/master/RuneApp/Program.cs#L312-L318).  When the new runes are loaded they are unlocked.  This block of code doesn't (re)lock all of the runes associated with a loadout... only runes that disappear.

**Comment by claytondaley** [comment]
We've addressed several major sources of this issue so I'm closing it in favor of #112 for tracking any persistent issues.
