### ISSUE TITLE
Ignore builds option can't be turned off

### ISSUE THREAD

**Issue by jipsuh** [Skibisky/RuneManager#31]
I noticed that the new "ignore builds < 5 % better" can't be turned off. Ticking it off doesn't stick, when you open the options menu again it will be ticked again.

**Comment by Skibisky** [comment]
Nice spot, fixed in 9b3a18d.  
If you don't want to wait until next release, you can change RuneManager.exe.config > setting name="IgnoreLess5" > "False", then reload the program.

**Comment by jipsuh** [comment]
Thanks, the workaround works nicely.
