### ISSUE TITLE
Don't Exclude Flats by Default (in Even slots)

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#34]
I get that flats normally aren't useful, but users should automatically sell those runes.

By contrast, a legendary flat may be kept if it triple- or quad-hits a SPD sub.  Excluding these runes by default will miss these (very important) runes.

**Comment by Skibisky** [comment]
I agree.
Additionally, if someone is keeping flats it's probably because they are good. Most people would be selling flats pretty fast.
