### ISSUE TITLE
Relocate and Rename SumN

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#38]
The name -- and having to put the count in `>=` -- are non-obvious.  It also prevents you from adding both a filter and weight at the same time.  I suggest making a TopN input box below the >= value (maybe only active if Sum is selected).

**Comment by Skibisky** [comment]
Yeah, I've put a 'Pick Top' box in, but haven't committed to cleaning out Sum/SumN (they sort of work the same now)
