### ISSUE TITLE
Refactor Methods to Eliminate Global Access

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#43]
I'm finally to the point that I could theoretically write a test case.  If you look at a method like `runBuilds`, it has arguments but also loads values from `Program.Settings`, `Program.data`, etc. -- I'm calling these "globals" though that may not be the right term in C#.

It'd be easier to write test cases if the method only used values from its arguments (i.e. no globals).  If you don't want to have a bunch of arguments, the caller can assemble an e.g. `BuildSettings` object that is passed as one of the arguments.  I'd define `BuildSettings` right next to `runBuilds` in the code so it could be extended if `runBuilds` gains additional features.

Obviously this simplifies test cases because I don't need to do a bunch of configuring of the globals... I just build the appropriate arguments and pass them.

**Comment by claytondaley** [comment]
If this isn't a standard pattern in C#, I could start to do some refactoring... but I know you're modifying code on your end and don't want to create conflicts.

**Comment by Skibisky** [comment]
The calls in the RuneApp project are specific to the UI and are calling code from RuneClasses.

It's a matter of picking the right entry point, but yes: it should be passed from the WinForms event.

I was poking some things last night, so I'll try and do a pass over this kind of stuff tonight and pur some commits up

**Comment by Skibisky** [comment]
Going back over the code the Program.runBuilds is a setup-teardown wrapper for the build.GenBuilds().
As part of upgrading the Build to BuildStrategies, I created BuildSettings, you can now pass that into the runBuilds.

The 'obsolete' GenBuilds() is going to stick around until I am okay with the stability of the BuildStrategies.
