### ISSUE TITLE
Don't Pre-Populate Required Columns

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#50]
I understand that this is a simple way to ensure a build is better, but I spend a ton of time deleting these values so I'd rather they not be populated at all.

![image](https://user-images.githubusercontent.com/1097439/71332824-4e777980-24fd-11ea-88de-538b62799cef.png)

**Comment by Skibisky** [comment]
For some reason a while back I decided to prefill the Required column if the Monster already had runes. The numbers are based on ~80% of the current stats.

Gonna get rid of it.
