### ISSUE TITLE
No Confirmation on Clear (All) Loadouts

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#53]
Obviously, this could destroy days of work with an accidental click.

**Comment by Skibisky** [comment]
Added a confirm dialogue with a total-time number.  
Don't forget the save/load buttons to store the generated loadouts. ![image](https://user-images.githubusercontent.com/17957029/79325911-960a9100-7f44-11ea-91a5-53bb675bfffb.png)
