### ISSUE TITLE
Inherit "Make+" Value in UI

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#59]
If you have the global value set to e.g. +12:

![image](https://user-images.githubusercontent.com/1097439/79081153-61969b00-7ce0-11ea-95af-f68cafcc1f68.png)

I believe the value on all of the descendant tabs should default to this unless overridden at another level by a different number.  For example, on the odds tab, the +12 should also show up here:

![image](https://user-images.githubusercontent.com/1097439/79081171-7e32d300-7ce0-11ea-85f8-262cb8bc0244.png)

This value would only change if the Odds box were actually used to override the inherited value.

**Comment by Skibisky** [comment]
Whoops, unsure how long this hasn't worked for :(  
Rejigged the prediction methods to help.
