### ISSUE TITLE
Refresh => Update Rune Locations

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#66]
This synchronizes with #63, espcially my new comment.  When working through FRR, it's nice to quickly see what's coming from inventory.  If I could restart and refresh (without recreating builds), I could see which monsters still need work and, ideally, which of the needed runes are now sitting in inventory.

I can't tell you how many times I've lost track of what units I had already modified.  If "refresh" cascaded to that right column (and visualization) it would save me incalculable hassle.

**Comment by claytondaley** [comment]
OK so this happens because the load process doesn't update `Loadout.Runes`.  Instead, they're left attached to the old orphaned Rune instances.

**Comment by Skibisky** [comment]
if you look between [ApiRenderer](https://github.com/Skibisky/RuneManager/blob/429eeb278d2bef6e65b135f92c63cbd6a355a44b/RuneApp/InternalServer/PageRenderers/ApiRenderer.cs#L303) and [RuneManager Bridge](https://github.com/Skibisky/RuneManager/blob/429eeb278d2bef6e65b135f92c63cbd6a355a44b/plugins/RuneManagerBridge/RuneManagerBridge.cs#L52), there is an internal HTTP server running on port 7676 that can take JSON payloads to trigger updates to the program, without having to reload the save.

It should be compatible with a SWEX JavaScript module plugin.

**Comment by claytondaley** [comment]
That's a cool idea (probably worthy of an Issue for "Realtime Updates from SWEX").  The bigger issue was that the data structure inside Loadouts weren't updated so they wouldn't render with the new info.
