### ISSUE TITLE
Repeating Build Uses Different Runes

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#68]
Simply running and clearing the build for my first unit (albeit after a few locked units) will generate a different set of runes each time it's rerun.  This last time, I noted it specifically on a unit where the runes changed (and only excluded runes that did change).  Perhaps the "remove loadout" feature needs to clear the rune reassignment slot and does not.

I'm thinking the same underlying issue could be the cause of #28.

**Comment by claytondaley** [comment]
P.S. are you still working on this program?

**Comment by claytondaley** [comment]
I've made progress chasing this down.  It appears to occur [here](https://github.com/Skibisky/RuneManager/blob/master/RuneClasses/BuildProcessing/Build.Old.cs#L285).  The short version is that the first time the monster was run, it appears that runes were `Locked`.  When you try to rerun the monster, this check finds a locked rune an doesn't release it.  This orphans the rune since it's no longer in the new build.

It's odd that this is in `Build.Old.cs` because my live system is still using it.

**Comment by claytondaley** [comment]
In fact all the build strategies seem to still use this.

**Comment by Skibisky** [comment]
> In fact all the build strategies seem to still use this.

Yeah, some of the new strategies pick a few of the functions from the .Old file, which is kinda a TODO.

Nice find.

**Comment by claytondaley** [comment]
OK so I no longer get this on the first unit I try, but am seeing this with subsequent builds so it needs reopened.

**Comment by claytondaley** [comment]
I just realized why.  I had the naming wrong.  I'm unlocking `Current` when I really need to unlock `Best` (if it exists).  I just happened to test on units with unchanged runes so the two were the same.  I'll PR in a second.

**Comment by claytondaley** [comment]
... so this is touching on the same issue with Loadout <=> Mon linkage.  There's no reference from Mon => best Loadout.  There's no MonID in Loadout to use to filter.  I just discovered and indirect link through Build.  Best.Current.BuildID => Build.  Then Build => Mon to mon.
