### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#70]
Just checking in on the project.  If it's abandoned, I may try to recruit someone from SW Reddit to make some upgrades.  The approach is way more time-efficient than SWOP.  I would have promoted it sooner but we never got the duplicate rune bug ironed out.

**Comment by Skibisky** [comment]
Are you still getting your runes from SW proxy? with the changes preventing things development has taken a back seat.

I have managed to use a custom OS to jank a user cert in, so I was planning on doing more once other things settle down.

**Comment by claytondaley** [comment]
I use SWEX (https://github.com/Xzandro/sw-exporter/releases) which has supported HTTPS for a long time so long as your device is IOS, Android <7.0 (I used an old Nexus tab) or rooted (e.g. emulators).
