### ISSUE TITLE
Auto Generate monsters.json?

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#71]
I figured out how to use the Swarfarm Export package to create an updated `skills.json` but that file didn't "fix" the unnamed monsters in my current instance.  My best guess is that `mosters.json` needs updated as well, but that looks like a really trivial Dictionary of `com2us_id` to `name`.  Is there some reason it can't be auto-generated at the same time?  I was going to try to add a step to the Swarfarm export, but figured there must be a reason why it wasn't happening automatically.

**Comment by claytondaley** [comment]
The loadouts issue has gone away, but I'm not clear if it happened because I replaced `monsterNames.json` as well  It seems to be the same as `monsters.json`.  Perhaps you know the difference off hand.

**Comment by Skibisky** [comment]
nice idea, can you believe I was manually typing out that Json file?

thanks
