### ISSUE TITLE
Provide Visual Indication of Rune Dial

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#75]
I have never double clicked on the rune dial to actually get that pop-up.  It's amazing!  You need to add a UI element so people actually find it..

**Comment by claytondaley** [comment]
I mean this would have saved me SOOOOOOOO much time reruning!

**Comment by Skibisky** [comment]
Yeah, I am unsure how to make it apparent and non-invasive.

**Comment by claytondaley** [comment]
Maybe an arrow button [ > ] below the sets.  Having a UI element prompts a user to try it.
